---
- name: Give the tomcat group ownership
  file:
    path: /opt/tomcat
    group: tomcat
    state: directory
    recurse: yes
- name: give the tomcat group read access to the conf directory
  file:
    path: /opt/tomcat/conf
    state: directory
    recurse: yes
    mode: g+r
- name: give the tomcat group execute access to the conf directory
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+x
- name: Make the tomcat user the owner webapps
  file:
    path: /opt/tomcat/webapps
    state: directory
    owner: tomcat
- name: Make the tomcat user the owner work
  file:
    path: /opt/tomcat/work
    state: directory
    owner: tomcat
- name: Make the tomcat user the owner temp
  file:
    path: /opt/tomcat/temp
    state: directory
    owner: tomcat
- name: Make the tomcat user the owner logs
  file:
    path: /opt/tomcat/logs
    state: directory
    owner: tomcat